### PR TITLE
Update for Vault 0.10

### PR DESCRIPTION
**Pull request by wjoel**
Plugins now have an additional context argument.

Vault core now handles lease TTLs for plugins.

I'm also making `BoundDomain` optional to make this usable with non-G Suite Google authentication, which allows me to authenticate with my vault using `my.name@gmail.com` - let me know if you'd prefer this as a separate commit. It's a small change.

I'm new to go dep, so it's possible that I didn't update the dependencies correctly. I had to add go-plugin explicitly, which doesn't feel right.

### CODE REVIEW

**Comment by tomwilkie** [comment]
Thanks @wjoel!  I'll give this a once over today.

**Comment by wjoel** [comment]
@tomwilkie anything I can do to help this get merged? Seems to work for others in https://github.com/grapeshot/google-auth-vault-plugin/issues/6

**Comment by tomwilkie** [comment]
Oh yeah, sorry! I’m in holiday right now but keep reminding me and I’ll
take a look. Alternatively @jrbaldry might be able to.

**Comment by tomwilkie** [comment]
@jdbaldry that would be.

**Comment by MartinLeedotOrg** [comment]
@tomwilkie reminder as requested :)

**Comment by bitglue** [comment]
@tomwilkie @jdbaldry rebump. I also confirm this works for Vault 0.10.4.

**Comment by vranystepan** [comment]
@tomwilkie @jdbaldry
Hi guys, I also confirm it works with v0.11.1. Or at least I was able to mount the plugin :)

**Comment by eric-cancil** [comment]
@tomwilkie 
Bump

**Comment by incr3m** [comment]
Can anyone help me to compile this package? Im using dockerfile below to build the binary:
```
FROM golang:1.11.2

RUN curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

WORKDIR /go/src/google-auth-vault-plugin

RUN git clone --depth 1 https://github.com/wjoel/google-auth-vault-plugin.git -b vault-0.10 .
RUN dep ensure -v
RUN go build -o google-auth-vault-plugin ./
```
i'm always getting the following error:
```
Solving failure: No versions of github.com/grapeshot/google-auth-vault-plugin met constraints:
    master: Could not introduce github.com/grapeshot/google-auth-vault-plugin@master, as it has a dependency on github.com/hashicorp/vault with constraint ^0.9.1, which has no overlap with existing constraint ^0.10.0 from (root)
```

**Comment by benleb** [comment]
Maybe check out https://github.com/jetstack/vault-plugin-auth-google

unfortunately this repo here seems dead since month...

**Comment by incr3m** [comment]
Thnx @benleb. The repo helped me progress. now Im having another issue https://github.com/jetstack/vault-plugin-auth-google/issues/1#issue-379802476

**Comment by wjoel** [comment]
Unfortunately the jetstack repo seems to be dead as well, but I'm closing this PR due to inactivity and because I'm no longer working on anything related to Vault.

**Pull request closed without merging**
