### PR TITLE
Update with things I discovered during setup

### PR DESCRIPTION
**Pull request by gergnz**

### CODE REVIEW

**Comment by tomwilkie** [comment]
Hi @gergnz; thanks for the PR!  

I've so far avoided promoting the groups features of this plugin, as the plugin itself needs admin rights to read the groups - which isn't a very secure deployment.  It works fine if the user logging in is an admin, but otherwise it fail.  If you can update your PR to mention that, I'd be happy to merge.

**Comment by gergnz** [comment]
Thanks for the extra detail @tomwilkie. How does that look?

**Comment by gergnz** [comment]
Updated. How's that?

**Comment by tomwilkie** [comment]
Perfect, sorry for the delay.

**Pull request merged**
